import { test, expect } from '@playwright/test';

const testTimestamp = Date.now();
const testIssueTitle = `Automated QA Ticket - ${testTimestamp}`;

test.describe('Jira Clone Critical Path', () => {

    test('User can create, assign, and track a ticket', async ({ page }) => {
    
        // --- PHASE 0: AUTHENTICATION ---
        // Navigate to your login page (adjust the URL if your route is different, like '/')
        await page.goto('http://localhost:3000/login');

        // Find the email and password fields and log in
        // NOTE: Update these locators if your input fields don't have these exact placeholders/labels
        await page.locator('input[type="email"]').fill('oudhatim07@gmail.com');
        await page.locator('input[type="password"]').fill('r4q3b6r5');
        
        // Click the login/submit button (adjust the name if your button says "Sign In" or something else)
        await page.getByRole('button', { name: /Log In/i }).click();

        // Wait for the app to successfully log in and redirect to the dashboard
        await page.waitForURL('**/dashboard**');


        // --- PHASE 1: CREATE ISSUE ---
        const projectId = '7a44867c-a96a-443a-bbe5-1a0737a7523a';
        await page.goto(`http://localhost:3000/dashboard/projects/${projectId}`);

        // Click the create button to open the modal
        await page.getByRole('button', { name: '+ Create Issue' }).click();

        // Fill out the modal text boxes
        await page.locator('div').filter({ hasText: /^Title$/ }).getByRole('textbox').fill(testIssueTitle);
        await page.locator('div').filter({ hasText: /^Description$/ }).getByRole('textbox').fill('This ticket was generated by an automated Playwright script.');

        // DEFINE THE PROMISE: Start listening for the POST request
        const createIssuePromise = page.waitForResponse(response =>
            response.url().includes('/api/issues/') && response.request().method() === 'POST'
        );

        // Click the final Create button to trigger the API call
        await page.getByRole('button', { name: 'Create', exact: true }).click();

        // Wait for the backend to confirm it saved to PostgreSQL!
        const createResponse = await createIssuePromise;
        expect(createResponse.status()).toBe(200);

        // Verify it visually appeared in the "To Do" column
        await expect(page.getByText(testIssueTitle)).toBeVisible();

        // --- PHASE 2: ASSIGNMENT ---

        // Click the newly created ticket card to open the Details Modal
        await page.getByText(testIssueTitle).click();

        // Listen for the PATCH request
        const patchIssuePromise = page.waitForResponse(response =>
            response.url().includes('/api/issues/') && response.request().method() === 'PATCH'
        );

        // Find the Assignee dropdown (Removed the strict ^$ regex so it finds the div safely!)
        const assigneeSelect = page.locator('label:has-text("Assignee") + select');
        
        await assigneeSelect.selectOption({ label: 'Hatim Oudghiri (Me)' });

        // Wait for the backend to confirm the update
        const patchResponse = await patchIssuePromise;
        expect(patchResponse.status()).toBe(200);

        // Close the modal
        await page.getByRole('button', { name: '×' }).click();

        // --- PHASE 3: VERIFY "MY TICKETS" DASHBOARD ---

        // Navigate to the My Tickets page via the sidebar
        await page.getByRole('link', { name: 'My Tickets' }).click();

        // Verify the URL changed
        await expect(page).toHaveURL('http://localhost:3000/dashboard/tickets');

        // Verify the newly assigned ticket appears in the personal list view
        await expect(page.getByRole('heading', { name: testIssueTitle })).toBeVisible();
        
        // Verify the status badge rendered correctly in the list
        const ticketRow = page.locator('li').filter({ hasText: testIssueTitle });
        await expect(ticketRow.getByText('TODO')).toBeVisible();
    });
});